name: pdf
description: Flutter client app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.4
  in_app_purchase: ^3.1.11

flutter:
  uses-material-design: true
